### ISSUE TITLE
Issue after upgrading typescript to 3.2.1

### ISSUE THREAD

**Issue by vsssunder** [peterolson/BigInteger.js#190]
I have upgraded typescriptnto 3.2.1 after which I am getting the following error:

ERROR in node_modules/typescript/lib/lib.dom.d.ts(17834,6): error TS2300: Duplicate identifier 'BigInteger'.
node_modules/@types/big-integer/index.d.ts(6,11): error TS2300: Duplicate identifier 'BigInteger'.
node_modules/@types/big-integer/index.d.ts(222,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'bigInt' must be of type 'BigIntegerStatic', but here has type 'BigIntegerStatic'.
